### **学习目标**
1. 张量的缩减操作
2. 访问张量中的数据

1.1 **张量缩减操作的定义**

In [2]:
# 张量的缩减操作是指将张量的某些维度进行压缩，减少张量中的元素数量，
# 从而得到一个新的张量。
# 我们所学的有关张量运算的都是在管理张量中包含的数据元素
# 上一节学习的元素操作是在两个张量之间的元素执行操作
# 缩减操作是对在一个张量中的元素执行操作

1.2 **第一个缩减操作**

In [3]:
import torch
import numpy as np
t = torch.tensor([
    [0, 1, 0],
    [2, 0, 2],
    [0, 3, 0]
], dtype = torch.float32)

In [4]:
t.sum()
# .sun()求张量中所有元素的和

tensor(8.)

In [5]:
t.numel()
# .numel()求张量中元素的个数

9

In [6]:
t.sum().numel()
# 求和后再求元素数量

1

In [7]:
t.sum().numel() < t.numel()
# 比较运算，可以看出在.sum()之后得到的个数是小于原本的个数的
# 减少了8个元素 9 - 1 =8

True

1.2 **结论：求和操作是一种缩减操作**

1.3 **其他的常见操作**

In [8]:
t.sum()

tensor(8.)

In [9]:
t.prod()
# `prod()`函数返回张量中所有元素的乘积。 

tensor(0.)

In [10]:
t.mean()
# `mean()`函数的作用是计算张量中所有元素的平均值。 

tensor(0.8889)

In [11]:
t.std()
# `std()`方法是用于计算张量中元素的标准差的函数。标准差是一种度量数据集合变化程度的指标。
# 标准差的计算公式为：标准差 = sqrt(平均数的平方 - 平方的平均数)
# sqrt用于计算一个数的平方根。

tensor(1.1667)

In [12]:
# 以上的所有样例都将张量缩减为一个元素的张量
# 通常，缩减操作可以用于计算张量的总和，平均值，最大值，最小值等。

1.3 **疑问：缩减操作总是会将一个张量缩减成一个元素的张量吗？**

**NO！**

1.4 **通常我们会在特定的轴缩减元素**

In [13]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype = torch.float32)

In [14]:
# 在特定的轴进行缩减操作，我们只需要传递轴的参数进去

In [15]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [16]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [17]:
# 这里的结果应该会有疑惑，我们结合前面的内容理解
t.dim(), t.shape, len(t.shape)
# t的形状和轴的数量

(2, torch.Size([3, 4]), 2)

In [18]:
# 目前的 t 张量有两个轴
# 还记得这两个输出吗
t[0], t[0][0]
# 第一个轴是数组，第二个轴为数字
# sum()是元素操作的一种
# 而元素操作
# 两个张量必须具有相同的形状才能进行元素操作，这样才能确保元素操作中的元素位置对应

(tensor([1., 1., 1., 1.]), tensor(1.))

In [19]:
t[0] + t[1] + t[2], t.sum(dim=0)

(tensor([6., 6., 6., 6.]), tensor([6., 6., 6., 6.]))

In [20]:
# 所以 ! 
t.sum(dim=0) == t[0] + t[1] + t[2]
# dim = 0 是第一个轴， 在 t 中第一个轴为数组 t[0] t[1] t[2]
# 将 t.sum(dim=0) 看成是 3 个包含 4 个元素的 1 维张量元素相加
# 形状相同才能相加，且元素操作对应
# 6 = 1 + 2 + 3
# 到这里我相信已经都明白了

tensor([True, True, True, True])

In [21]:
# 同理
# 对第二个轴进行求和

In [22]:
t[0].sum(), t[1].sum(), t[2].sum(), t.sum(dim=1)

(tensor(4.), tensor(8.), tensor(12.), tensor([ 4.,  8., 12.]))

In [23]:
t.sum(dim=1) == torch.tensor([t[0].sum(), t[1].sum(), t[2].sum()])
# 这里可以看成 4 个 包含 1 个元素的 0 维张量求和
# 4 = 1 + 1 + 1 + 1 以此类推

tensor([True, True, True])

1.5 **常见的缩减操作 ArgMax**

In [24]:
# Argmax是一个数学函数：会返回一个张量中最大值的索引

In [25]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [26]:
t.max()
# 张量中的最大值

tensor(5.)

In [27]:
t.argmax()
# 张量中最大值的索引
# 这里使用的是 flatten()后的一维张量的索引

tensor(11)

In [28]:
t.flatten()
# 将张量展平为一维张量

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [29]:
# 在特定轴处理

In [30]:
t.max(dim=0), t.max(dim=1)
# dim=0 这个轴是数组组成的
# 元素操作中的比较，对应位置进行比较，1 和 0 和 4 进行比较，以此类推
# 即返回各列的最大值组成的 1 维张量

# dim=1 这个轴是数字组成的
# 元素操作中的比较，对应位置进行比较，1 和 0 和 0 和 2 进行比较，以此类推
# 即返回各行的最大值组成的 1 维张量

(torch.return_types.max(
 values=tensor([4., 3., 3., 5.]),
 indices=tensor([2, 1, 1, 2])),
 torch.return_types.max(
 values=tensor([2., 3., 5.]),
 indices=tensor([3, 1, 3])))

In [31]:
t.argmax(dim=0), t.argmax(dim=1)
# dim=0返回的索引是在[0, 1, 2]之间中的一个数
# dim=1返回的索引是在[0, 1, 2, 3]之间的一个数
# 如果感觉理解不适， 试试理解 dim=1 是在 dim=0 的基础上的建立的

# 即 dim = 0 包含
# [ ， ， ， ，]
# [ ， ， ， ，]
# [ ， ， ， ，]
# 其中每个张量包含了4个元素，进行元素操作时是 4 个一行对应位置进行比较，一行一行比较
# 这里的一行一行，是一整行与一整行进行比较
# 这也是为什么 dim = 0 时返回的是 4 个元素

# 而 dim = 1 是
# [1, 0, 0, 2]里面的数字1，0，0，2
# 其中每个张量都是 0 维张量，进行元素操作时候，即 1 和 0 和 0 和 2进行元素操作
# 也可以理解成一行一行比较，但是是在一行一行的内部进行的
# dim=1 是在 dim=0 的基础上的建立的
# 这样的一维张量有 3 个
# 这也是为什么dim = 1 返回的是 3 个元素
# 后面以此类推

# dim = 0 时返回的是 4 个元素，dim = 1 返回的是 3 个元素

(tensor([2, 1, 1, 2]), tensor([3, 1, 3]))

In [32]:
# 使用argmax函数可以沿着一个轴找到最大值的索引。
# 它在许多应用中非常有用，例如在分类任务中找到最可能的类。
# 在输出预测张量时使用argmax函数可以沿着一个轴找到最大值的索引。
# 让我们确定哪个类别的预测值最高。

2.1 **访问标量张量中的值**

In [33]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [34]:
t.mean()
# 获得张量的均值，返回的是一个标量张量

tensor(5.)

In [35]:
t.mean().item()
# 转换作为数字输出，也可称访问这个标量张量中的值。
# item()将张量中的单个值转换为Python数值并返回。
# item()只针对！标量张量，即 0 维张量

5.0

2.2 **访问一个张量中的多个值**

In [36]:
t.mean(dim=0).tolist(), t.mean(dim=1).tolist()
# tolist()将张量转换为Python列表的方法。
# 这里也可以测试对dim = 0 和 dim = 1的掌握程度

([4.0, 5.0, 6.0], [2.0, 5.0, 8.0])

In [40]:
t[0], t[0].tolist()

(tensor([1., 2., 3.]), [1.0, 2.0, 3.0])